spring.application.name=WorkFlowApproval

spring.datasource.url=jdbc:h2:mem:workflow
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.username=sa
spring.datasource.password=

spring.security.user.name=admin
spring.security.user.password=admin

server.error.include-message=always
server.error.include-stacktrace=never
